### PR TITLE
feat: add device routes

### PR DESCRIPTION
**Pull request by denouche**

### CODE REVIEW

**Comment by josephpage** [comment]
You should add tips about how/where to find the Xee ID and the PIN, with examples. And it will be good to me.

**Comment by alexjomin** [comment]
@josephpage do you mean on the packaging ?

**Comment by josephpage** [comment]
Yes photos of a box, with exemple of valid numbers (eg: `E000000000` for the Xee ID, `1234` for the PIN).
Also how to retrieve them when the box was put in the trash.

**Comment by quentin7b** [comment]
Maybe the same picture we put in the instructions for use.

**Comment by quentin7b** [comment]
Misses the links to devices routes in https://github.com/xee-lab/xee-api-docs/tree/master/api/api/v3 ?

**Comment by josephpage** [comment]
I just saw the PIN is written on a small sticker on the cable of the box.
You should just put this information in the documentation.

**Comment by josephpage** [comment]
@quentin7b I've added the routes on the API index : #63

**Pull request merged**
